window.LYRICS_API_ENDPOINT = window.LYRICS_API_ENDPOINT || '';
window.LYRICS_SEARCH_API_ENDPOINT = window.LYRICS_SEARCH_API_ENDPOINT || '';
window.COVER_API_ENDPOINT = window.COVER_API_ENDPOINT || '';
